<?php


$title = 'Add new comentario';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php


// This provides a default CSS class and placeholder text for the post element:
$post = $form->get('post');
$post->setAttribute('class', 'form-control');
$post->setAttribute('placeholder', 'Post');

// This provides a default CSS class and placeholder text for the comentario element:
$comentario = $form->get('comentario');
$comentario->setAttribute('class', 'form-control');
$comentario->setAttribute('placeholder', 'Comentario');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');


$form->setAttribute('action', $this->url('comentario', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>


<div class="form-group">
    <?= $this->formLabel($post) ?>
    <?= $this->formElement($post) ?>
    <?= $this->formElementErrors()->render($post, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($comentario) ?>
    <?= $this->formElement($comentario) ?>
    <?= $this->formElementErrors()->render($comentario, ['class' => 'help-block']) ?>
</div>



<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
