<?php
// module/Comentario/view/comentario/comentario/edit.phtml:

$title = 'Edit comentario';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$post = $form->get('post');
$post->setAttribute('class', 'form-control');
$post->setAttribute('placeholder', 'Post');

$comentario = $form->get('comentario');
$comentario->setAttribute('class', 'form-control');
$comentario->setAttribute('placeholder', 'Comentario');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('comentario', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($post) ?>
    <?= $this->formElement($post) ?>
    <?= $this->formElementErrors()->render($post, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($comentario) ?>
    <?= $this->formElement($comentario) ?>
    <?= $this->formElementErrors()->render($comentario, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
